### ISSUE TITLE
Whatsapp for windows link crashes the app

### ISSUE THREAD

**Issue by shuvashish76** [92lleo/WhatsappWebToGo#116]
Crashes if you click "Get the app" link.

Logs:
```
FATAL EXCEPTION: main
Process: io.kuenzler.whatsappwebtogo, PID: 18739
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=ms-windows-store://pdp/?productid=9NKSQGP7F2NH&mode=mini&cid=68a40a }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2181)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1812)
	at android.app.Activity.startActivityForResult(Activity.java:5506)
	at androidx.activity.ComponentActivity.startActivityForResult(Unknown Source:0)
	at android.app.Activity.startActivityForResult(Activity.java:5464)
	at androidx.activity.ComponentActivity.startActivityForResult(Unknown Source:0)
	at android.app.Activity.startActivity(Activity.java:5854)
	at android.app.Activity.startActivity(Activity.java:5807)
	at io.kuenzler.whatsappwebtogo.WebviewActivity$c.shouldOverrideUrlLoading(Unknown Source:65)
	at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-SystemWebView.apk-stable-593806001:93)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:342)
	at android.os.Looper.loopOnce(Looper.java:182)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8090)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
```

**Comment by 92lleo** [comment]
can reproduce, will look into it

**Comment by 92lleo** [comment]
see #118
